# Loads only repository functions; no real service, registry or trust-store mutation.
param([string]$ScriptPath = (Join-Path $PSScriptRoot '..\uninstall.ps1'))
$ErrorActionPreference = 'Stop'
$tokens = $null; $errors = $null
$ast = [System.Management.Automation.Language.Parser]::ParseFile((Resolve-Path $ScriptPath), [ref]$tokens, [ref]$errors)
if ($errors.Count) { throw ($errors | Out-String) }
$ast.FindAll({ param($node) $node -is [System.Management.Automation.Language.FunctionDefinitionAst] }, $false) | ForEach-Object {
  . ([ScriptBlock]::Create($_.Extent.Text))
}
$ScriptLang = 'en'
$NonInteractive = $true
$Yes = $false
$KeepConfig = $false
$Purge = $true
$CallerPID = 0
$temp = Join-Path ([IO.Path]::GetTempPath()) ('vg-uninstall-ps-test-' + [Guid]::NewGuid())
New-Item -ItemType Directory $temp | Out-Null
try {
  # Missing cert after successful purge is idempotent, not an untrust failure.
  if (-not (TryUntrustCA $temp)) { throw 'Missing CA must allow repeated uninstall' }
  # Parse the PEM format generated by VibeGuard, without localized certutil output.
  $rsa = [Security.Cryptography.RSA]::Create(2048)
  $request = [Security.Cryptography.X509Certificates.CertificateRequest]::new('CN=VibeGuard Synthetic Test', $rsa, [Security.Cryptography.HashAlgorithmName]::SHA256, [Security.Cryptography.RSASignaturePadding]::Pkcs1)
  $certificate = $request.CreateSelfSigned([DateTimeOffset]::Parse('2020-01-01'), [DateTimeOffset]::Parse('2030-01-01'))
  $certPath = Join-Path $temp 'synthetic.crt'
  $base64 = [Convert]::ToBase64String($certificate.Export([Security.Cryptography.X509Certificates.X509ContentType]::Cert), [Base64FormattingOptions]::InsertLineBreaks)
  [IO.File]::WriteAllText($certPath, "-----BEGIN CERTIFICATE-----`n$base64`n-----END CERTIFICATE-----`n")
  if ((GetCAThumbprintFromFile $certPath) -ne $certificate.Thumbprint) { throw 'PEM thumbprint mismatch' }
  $certificate.Dispose(); $rsa.Dispose()
  # Unreadable stores must never be interpreted as absence of trust.
  function Get-ChildItem { throw 'Synthetic trust-store access failure' }
  $failed = $false
  try { IsThumbprintInStore 'Cert:\CurrentUser\Root' 'synthetic' | Out-Null } catch { $failed = $true }
  if (-not $failed) { throw 'Trust query failure was ignored' }
  Remove-Item Function:\Get-ChildItem
  # Preserve caller and unrelated stale PIDs; only stop the installed binary.
  $InstallDir = $temp
  $vg = Join-Path $temp 'vibeguard.exe'
  $script:stopped = @()
  function Get-Process { param($Id) [PSCustomObject]@{ Id = $Id; Path = 'unrelated.exe' } }
  function Stop-Process { param($Id) $script:stopped += $Id }
  StopVibeGuardProcess 123 $vg
  if ($script:stopped.Count) { throw 'Killed unrelated PID' }
  function Get-Process { param($Id) [PSCustomObject]@{ Id = $Id; Path = $vg; HasExited = $true } }
  $CallerPID = 123
  StopVibeGuardProcess 123 $vg
  if ($script:stopped.Count) { throw 'Killed uninstall caller' }
  $CallerPID = 0
  StopVibeGuardProcess 123 $vg
  if ($script:stopped.Count -ne 1) { throw 'Did not stop installed proxy' }
  Remove-Item Function:\Get-Process, Function:\Stop-Process
  # The profile helper has nested braces; user content after it must survive.
  $profile = Join-Path $temp 'profile.ps1'
  [IO.File]::WriteAllText($profile, "`$before=1`n# VibeGuard SHELL`nfunction vibeguard {`n  if (`$true) {`n    'test'`n  }`n}`n`$after=2`n")
  RemoveProfileHelper $profile | Out-Null
  $text = Get-Content $profile -Raw
  if ($text.Contains('VibeGuard') -or -not $text.Contains('$before=1') -or -not $text.Contains('$after=2')) { throw 'Profile cleanup lost user content' }
  # Worker uses a wait handle, bounded retries and an explicit success/failure receipt.
  $worker = NewBinaryRemovalScript $vg 123 (Join-Path $temp 'result.txt')
  foreach ($term in @('WaitForExit', 'Remove-Item', 'complete', 'failed')) {
    if (-not $worker.Contains($term)) { throw "Worker missing $term" }
  }
  $workerErrors = $null
  [System.Management.Automation.Language.Parser]::ParseInput($worker, [ref]$tokens, [ref]$workerErrors) | Out-Null
  if ($workerErrors.Count) { throw ($workerErrors | Out-String) }
  # Exercise the worker itself (using this already-exited PID is unnecessary).
  $target = Join-Path $temp "binary with 'quote.exe"
  Set-Content -LiteralPath $target 'synthetic binary'
  $receipt = Join-Path $temp 'receipt.txt'
  & ([ScriptBlock]::Create((NewBinaryRemovalScript $target 0 $receipt)))
  if ((Test-Path -LiteralPath $target) -or (Get-Content $receipt -Raw).Trim() -ne 'complete') { throw 'Worker did not remove binary' }
  Write-Host 'PowerShell uninstall regression tests passed'
} finally {
  Remove-Item -LiteralPath $temp -Recurse -Force
}
