package config

import (
	"log/slog"
	"os"
	"path/filepath"
	"strings"
	"sync"

	"github.com/fsnotify/fsnotify"
	"gopkg.in/yaml.v3"
)

// Config represents the main configuration structure
type Config struct {
	Proxy    ProxyConfig    `yaml:"proxy"`
	Patterns PatternsConfig `yaml:"patterns"`
	Targets  []TargetConfig `yaml:"targets"`
	Session  SessionConfig  `yaml:"session"`
	Log      LogConfig      `yaml:"log"`
	// AuditDB controls whether audit events are persisted to SQLite (only available in the "full" build; disabled by default).
	AuditDB AuditDBConfig `yaml:"audit_db"`
}

// ProxyConfig holds proxy server settings
type ProxyConfig struct {
	Listen            string `yaml:"listen"`
	PlaceholderPrefix string `yaml:"placeholder_prefix"`
	// InterceptMode controls how HTTPS CONNECT is handled:
	// - global: MITM for all hosts (default; best for HTTP(S)_PROXY env usage)
	// - targets: MITM only for enabled hosts in targets (safer; avoids impacting non-target traffic)
	InterceptMode string `yaml:"intercept_mode"`
	// WebSocketRedactionBeta enables best-effort WebSocket text-message redaction/restore.
	// It is intentionally off by default because some servers/extensions may be incompatible.
	WebSocketRedactionBeta bool `yaml:"websocket_redaction_beta"`
}

// PatternsConfig holds pattern matching configuration
type PatternsConfig struct {
	Keywords    []KeywordPattern   `yaml:"keywords"`
	Regex       []RegexPattern     `yaml:"regex"`
	Builtin     []string           `yaml:"builtin"`
	Exclude     []string           `yaml:"exclude"`
	SecretFiles []SecretFileConfig `yaml:"secret_files"`
	RuleLists   []RuleListConfig   `yaml:"rule_lists"`
	// NER toggles and configures named-entity recognition (external Presidio engine; off by default).
	NER NERConfig `yaml:"ner"`
}

// NERConfig controls the optional NER-based recognizers (e.g. PERSON/ORG/LOCATION).
// Note: this config does not contain sensitive data; it only controls enablement and entity types.
type NERConfig struct {
	Enabled bool `yaml:"enabled"`
	// PresidioURL is the Presidio Analyzer service URL (e.g. http://127.0.0.1:5001).
	// Note: VibeGuard does not bundle Presidio; it only calls an external service.
	PresidioURL string `yaml:"presidio_url"`
	// Language is passed to Presidio (e.g. en / zh / fr ...).
	// Note: Presidio requires a language; for backward compatibility, "auto" is treated as "en".
	Language string `yaml:"language"`
	// Entities specifies enabled entity types (e.g. PERSON/ORG/LOCATION/DATE...). Empty means the implementation default set.
	Entities []string `yaml:"entities"`
	// MinScore is the Presidio confidence threshold (0~1; 0 means Presidio default).
	MinScore float64 `yaml:"min_score"`
}

// RuleListConfig describes a rule list file (line-based rules).
type RuleListConfig struct {
	// ID is a stable identifier (generated by the admin UI); may be empty.
	ID string `yaml:"id" json:"id"`
	// Name is a display name (editable in the admin UI); may be empty.
	Name string `yaml:"name" json:"name"`
	// Path is the local rule file path (supports ~); mutually exclusive with URL.
	Path string `yaml:"path" json:"path"`
	// URL is the remote subscription URL (http/https); mutually exclusive with Path.
	URL string `yaml:"url" json:"url"`
	// UpdateInterval is the subscription update interval (e.g. 24h/6h); applies to URL mode only. Default is 24h.
	UpdateInterval string `yaml:"update_interval" json:"update_interval"`
	// AllowHTTP allows http:// subscriptions when true (unsafe; default only allows https://).
	AllowHTTP bool `yaml:"allow_http" json:"allow_http"`
	// Enabled controls whether this rule list participates in matching.
	Enabled bool `yaml:"enabled" json:"enabled"`
	// Priority controls priority (1~99); higher wins on overlaps.
	Priority int `yaml:"priority" json:"priority"`
}

// KeywordPattern represents a keyword to match
type KeywordPattern struct {
	Value    string `yaml:"value" json:"value"`
	Category string `yaml:"category" json:"category"`
}

// RegexPattern represents a regex pattern to match
type RegexPattern struct {
	Pattern  string `yaml:"pattern" json:"pattern"`
	Category string `yaml:"category" json:"category"`
}

// SecretFileConfig describes a local file whose contents should be treated as secrets and redacted if they appear in prompts.
// Note: this does not prevent the client from reading files; it only prevents accidental exfiltration to upstream LLM APIs.
type SecretFileConfig struct {
	// Path is a local file path (supports ~). Relative paths are resolved relative to the config file that defined it.
	Path string `yaml:"path" json:"path"`
	// Format controls how the file is parsed:
	// - dotenv: parse KEY=VALUE lines and import VALUEs as keywords (recommended for .env)
	// - lines: treat each non-empty non-comment line as a keyword
	Format string `yaml:"format" json:"format"`
	// Category is the match category used in audit/logging. Defaults to DOTENV/SECRET_FILE based on format.
	Category string `yaml:"category" json:"category"`
	// MinValueLen filters out short values to reduce false positives. Default is 8.
	MinValueLen int `yaml:"min_value_len" json:"min_value_len"`
	// Enabled defaults to true when omitted.
	Enabled *bool `yaml:"enabled" json:"enabled"`
}

// TargetConfig represents a target host configuration
type TargetConfig struct {
	Host    string `yaml:"host"`
	Enabled bool   `yaml:"enabled"`
}

// SessionConfig holds session management settings
type SessionConfig struct {
	TTL                       string `yaml:"ttl"`
	MaxMappings               int    `yaml:"max_mappings"`
	WALEnabled                bool   `yaml:"wal_enabled"`
	WALPath                   string `yaml:"wal_path"`
	DeterministicPlaceholders bool   `yaml:"deterministic_placeholders"`
}

// LogConfig holds logging configuration
type LogConfig struct {
	Level     string `yaml:"level"`
	File      string `yaml:"file"`
	RedactLog bool   `yaml:"redact_log"`
}

// AuditDBConfig holds SQLite audit persistence settings.
// Note: when enabled, audit events are written to disk (by default only preview values are persisted;
// if privacy mode is disabled, truncated originals may be persisted).
type AuditDBConfig struct {
	Enabled bool `yaml:"enabled"`
	// Path is the SQLite file path (supports ~).
	Path string `yaml:"path"`
	// Retention is the retention duration (time.ParseDuration; also supports "7d" for days).
	Retention string `yaml:"retention"`
}

// Default configuration values
var defaultConfig = Config{
	Proxy: ProxyConfig{
		Listen:                 "127.0.0.1:28657",
		PlaceholderPrefix:      "__VG_",
		InterceptMode:          "global",
		WebSocketRedactionBeta: false,
	},
	Patterns: PatternsConfig{
		Keywords:    []KeywordPattern{},
		Regex:       []RegexPattern{},
		Builtin:     []string{},
		Exclude:     []string{},
		SecretFiles: []SecretFileConfig{},
		RuleLists: []RuleListConfig{
			{
				ID:   "vibeguard-default",
				Name: "VibeGuard Default Rules",
				// Remote subscription (default rule set): maintained by the project and updated periodically by update_interval.
				// Note: a GitHub blob URL is acceptable; it will be normalized to a raw URL at runtime.
				URL:      "https://raw.githubusercontent.com/inkdust2021/vgrules/refs/heads/main/default.vgrules",
				Enabled:  true,
				Priority: 50,
			},
		},
		NER: NERConfig{
			Enabled:     false,
			PresidioURL: "",
			Language:    "en",
			Entities:    []string{},
			MinScore:    0,
		},
	},
	Targets: []TargetConfig{
		{Host: "api.anthropic.com", Enabled: true},
		{Host: "api.openai.com", Enabled: true},
		{Host: "api2.cursor.sh", Enabled: true},
		{Host: "generativelanguage.googleapis.com", Enabled: true},
	},
	Session: SessionConfig{
		TTL:                       "1h",
		MaxMappings:               100000,
		WALEnabled:                true,
		WALPath:                   "~/.vibeguard/session.wal",
		DeterministicPlaceholders: false,
	},
	Log: LogConfig{
		Level:     "info",
		File:      "~/.vibeguard/vibeguard.log",
		RedactLog: true,
	},
	AuditDB: AuditDBConfig{
		Enabled:   false,
		Path:      "~/.vibeguard/audit.db",
		Retention: "7d",
	},
}

// ConfigPath returns the expanded config file path
func ConfigPath() string {
	if cfgPath := os.Getenv("VIBEGUARD_CONFIG"); cfgPath != "" {
		return expandPath(cfgPath)
	}
	return filepath.Join(homeDir(), ".vibeguard", "config.yaml")
}

// ProjectConfigPath returns the project-level config path
func ProjectConfigPath() string {
	return ".vibeguard.yaml"
}

// homeDir returns the user's home directory
func homeDir() string {
	if home := os.Getenv("HOME"); home != "" {
		return home
	}
	return os.Getenv("USERPROFILE") // Windows
}

// GetConfigDir returns the config directory path
func GetConfigDir() string {
	return filepath.Join(homeDir(), ".vibeguard")
}

// GetRulesDir returns the rules directory path (for local rule lists and subscription cache).
func GetRulesDir() string {
	return filepath.Join(homeDir(), ".vibeguard", "rules")
}

// Load loads configuration from the given file path
func Load(cfgFile string) (*Manager, error) {
	m := NewManager()

	// Determine config path
	var configPath string
	if cfgFile != "" {
		configPath = expandPath(cfgFile)
	} else {
		configPath = ConfigPath()
	}
	if abs, err := filepath.Abs(configPath); err == nil {
		configPath = abs
	}
	m.configPath = configPath

	projectPath := ProjectConfigPath()
	if abs, err := filepath.Abs(projectPath); err == nil {
		projectPath = abs
	}
	m.projectPath = projectPath
	if err := m.Load(); err != nil {
		return nil, err
	}
	return m, nil
}

// expandPath expands ~ in path
func expandPath(path string) string {
	if strings.HasPrefix(path, "~/") {
		return filepath.Join(homeDir(), path[2:])
	}
	if strings.HasPrefix(path, "~"+string(os.PathSeparator)) {
		return filepath.Join(homeDir(), path[2:])
	}
	return path
}

func resolveRelativePath(baseDir, path string) string {
	path = strings.TrimSpace(path)
	if path == "" {
		return ""
	}
	path = expandPath(path)
	if filepath.IsAbs(path) {
		return path
	}
	if strings.TrimSpace(baseDir) == "" {
		return path
	}
	return filepath.Clean(filepath.Join(baseDir, path))
}

// DataDir returns the data directory path
func DataDir() string {
	return filepath.Join(homeDir(), ".vibeguard")
}

// Manager handles config loading, merging, and hot-reload
type Manager struct {
	mu      sync.RWMutex
	config  Config
	watcher *fsnotify.Watcher
	// configPath is the global config file path (used for read/write and fsnotify). When set via CLI --config, this path is used.
	configPath string
	// projectPath is the project-level override path (default: .vibeguard.yaml).
	projectPath string
	// patternCrypto persists patterns.keywords/exclude values in encrypted form (in-memory values remain plaintext).
	// This requires the caller to inject a key (typically derived from the CA private key).
	patternCrypto *patternCrypto
}

// NewManager creates a new config manager
func NewManager() *Manager {
	globalPath := ConfigPath()
	if abs, err := filepath.Abs(globalPath); err == nil {
		globalPath = abs
	}
	projectPath := ProjectConfigPath()
	if abs, err := filepath.Abs(projectPath); err == nil {
		projectPath = abs
	}
	return &Manager{
		config:      defaultConfig,
		configPath:  globalPath,
		projectPath: projectPath,
	}
}

// Load loads configuration from file
func (m *Manager) Load() error {
	m.mu.Lock()
	defer m.mu.Unlock()

	// Start with default config
	cfg := defaultConfig

	// Load global config if exists
	globalPath := m.configPath
	if globalPath == "" {
		globalPath = ConfigPath()
	}
	if data, err := os.ReadFile(globalPath); err == nil {
		if err := yaml.Unmarshal(data, &cfg); err != nil {
			return err
		}
		if len(cfg.Patterns.SecretFiles) > 0 {
			baseDir := filepath.Dir(globalPath)
			for i := range cfg.Patterns.SecretFiles {
				cfg.Patterns.SecretFiles[i].Path = resolveRelativePath(baseDir, cfg.Patterns.SecretFiles[i].Path)
			}
		}
		slog.Debug("Loaded config", "path", globalPath)
	} else if !os.IsNotExist(err) {
		return err
	}

	// Load project config if exists (merges with global)
	projectPath := m.projectPath
	if projectPath == "" {
		projectPath = ProjectConfigPath()
	}
	if data, err := os.ReadFile(projectPath); err == nil {
		var projectCfg Config
		if err := yaml.Unmarshal(data, &projectCfg); err != nil {
			return err
		}
		if len(projectCfg.Patterns.SecretFiles) > 0 {
			baseDir := filepath.Dir(projectPath)
			for i := range projectCfg.Patterns.SecretFiles {
				projectCfg.Patterns.SecretFiles[i].Path = resolveRelativePath(baseDir, projectCfg.Patterns.SecretFiles[i].Path)
			}
		}
		// Merge configs
		cfg = mergeConfigs(cfg, projectCfg)
		slog.Debug("Merged project config", "path", projectPath)
	} else if !os.IsNotExist(err) {
		return err
	}

	// If "pattern value at-rest encryption" is enabled, decrypt persisted ciphertext into plaintext before sanitizing.
	if err := m.decryptLoadedPatterns(&cfg); err != nil {
		return err
	}

	// Normalize config: strip invisible chars, normalize categories, etc, to avoid "configured but not effective" surprises.
	sanitizeLoadedConfig(&cfg)

	m.config = cfg
	return nil
}

func sanitizeLoadedConfig(cfg *Config) {
	if cfg == nil {
		return
	}

	// Proxy
	cfg.Proxy.Listen = strings.TrimSpace(cfg.Proxy.Listen)
	cfg.Proxy.PlaceholderPrefix = strings.TrimSpace(cfg.Proxy.PlaceholderPrefix)
	cfg.Proxy.InterceptMode = strings.TrimSpace(cfg.Proxy.InterceptMode)

	// Patterns: keywords
	if len(cfg.Patterns.Keywords) > 0 {
		out := make([]KeywordPattern, 0, len(cfg.Patterns.Keywords))
		for _, kw := range cfg.Patterns.Keywords {
			val := SanitizePatternValue(kw.Value)
			if val == "" {
				continue
			}
			cat := SanitizeCategory(kw.Category)
			if cat == "" {
				cat = "TEXT"
			}
			out = append(out, KeywordPattern{Value: val, Category: cat})
		}
		cfg.Patterns.Keywords = out
	}

	// Patterns: exclude
	if len(cfg.Patterns.Exclude) > 0 {
		out := make([]string, 0, len(cfg.Patterns.Exclude))
		for _, ex := range cfg.Patterns.Exclude {
			val := SanitizePatternValue(ex)
			if val == "" {
				continue
			}
			out = append(out, val)
		}
		cfg.Patterns.Exclude = out
	}

	// Patterns: secret_files
	if len(cfg.Patterns.SecretFiles) > 0 {
		out := make([]SecretFileConfig, 0, len(cfg.Patterns.SecretFiles))
		seen := make(map[string]struct{}, len(cfg.Patterns.SecretFiles))
		for _, sf := range cfg.Patterns.SecretFiles {
			path := strings.TrimSpace(sf.Path)
			if path == "" {
				continue
			}
			path = expandPath(path)

			format := strings.ToLower(strings.TrimSpace(sf.Format))
			if format == "" {
				format = "dotenv"
			}

			cat := SanitizeCategory(sf.Category)
			if cat == "" {
				if format == "lines" {
					cat = "SECRET_FILE"
				} else {
					cat = "DOTENV"
				}
			}

			minLen := sf.MinValueLen
			if minLen <= 0 {
				minLen = 8
			}
			if minLen > 1024 {
				minLen = 1024
			}

			enabled := true
			if sf.Enabled != nil {
				enabled = *sf.Enabled
			}

			key := format + ":" + path
			if _, ok := seen[key]; ok {
				continue
			}
			seen[key] = struct{}{}

			out = append(out, SecretFileConfig{
				Path:        path,
				Format:      format,
				Category:    cat,
				MinValueLen: minLen,
				Enabled:     &enabled,
			})
		}
		cfg.Patterns.SecretFiles = out
	}

	// Patterns: rule_lists
	if len(cfg.Patterns.RuleLists) > 0 {
		out := make([]RuleListConfig, 0, len(cfg.Patterns.RuleLists))
		seen := make(map[string]struct{}, len(cfg.Patterns.RuleLists))
		for _, rl := range cfg.Patterns.RuleLists {
			path := strings.TrimSpace(rl.Path)
			url := strings.TrimSpace(rl.URL)
			if path == "" && url == "" {
				continue
			}
			// Backward-compat: migrate the default subscription URL only when it still uses the old default value (avoid overwriting user customizations).
			if strings.TrimSpace(rl.ID) == "vibeguard-default" && strings.TrimSpace(url) == "https://raw.githubusercontent.com/inkdust2021/vgrules/main/default.vgrules" {
				url = "https://raw.githubusercontent.com/inkdust2021/vgrules/refs/heads/main/default.vgrules"
			}
			id := SanitizePatternValue(rl.ID)
			name := SanitizePatternValue(rl.Name)
			updateInterval := strings.TrimSpace(rl.UpdateInterval)
			allowHTTP := rl.AllowHTTP
			if url != "" && updateInterval == "" {
				updateInterval = "24h"
			}
			priority := rl.Priority
			if priority <= 0 {
				priority = 50
			}
			if priority > 99 {
				priority = 99
			}

			// Dedup key: prefer ID; otherwise dedup by Path/URL to avoid duplicate loads (confusing and wasteful).
			key := id
			if key == "" {
				if path != "" {
					key = "path:" + path
				} else {
					key = "url:" + url
				}
			}
			if _, ok := seen[key]; ok {
				continue
			}
			seen[key] = struct{}{}

			out = append(out, RuleListConfig{
				ID:   id,
				Name: name,
				Path: path,
				URL:  url,
				// Applies to URL mode only; Path mode keeps the value but does not use it.
				UpdateInterval: updateInterval,
				AllowHTTP:      allowHTTP,
				Enabled:        rl.Enabled,
				Priority:       priority,
			})
		}
		cfg.Patterns.RuleLists = out
	}

	// Patterns: regex/builtin are not editable in the admin UI currently, but still sanitize to prevent category issues that break restore.
	if len(cfg.Patterns.Regex) > 0 {
		out := make([]RegexPattern, 0, len(cfg.Patterns.Regex))
		for _, rp := range cfg.Patterns.Regex {
			pat := strings.TrimSpace(rp.Pattern)
			if pat == "" {
				continue
			}
			cat := SanitizeCategory(rp.Category)
			if cat == "" {
				cat = "REGEX"
			}
			out = append(out, RegexPattern{Pattern: pat, Category: cat})
		}
		cfg.Patterns.Regex = out
	}

	if len(cfg.Patterns.Builtin) > 0 {
		out := make([]string, 0, len(cfg.Patterns.Builtin))
		for _, b := range cfg.Patterns.Builtin {
			v := strings.TrimSpace(b)
			if v == "" {
				continue
			}
			out = append(out, v)
		}
		cfg.Patterns.Builtin = out
	}

	// Patterns: ner
	cfg.Patterns.NER.PresidioURL = strings.TrimSpace(cfg.Patterns.NER.PresidioURL)
	if lang := SanitizeNERLanguage(cfg.Patterns.NER.Language); lang != "" {
		cfg.Patterns.NER.Language = lang
	} else if strings.TrimSpace(cfg.Patterns.NER.Language) == "" {
		cfg.Patterns.NER.Language = defaultConfig.Patterns.NER.Language
	} else {
		// Invalid value: fall back to default.
		cfg.Patterns.NER.Language = defaultConfig.Patterns.NER.Language
	}
	if len(cfg.Patterns.NER.Entities) > 0 {
		out := make([]string, 0, len(cfg.Patterns.NER.Entities))
		for _, e := range cfg.Patterns.NER.Entities {
			v := SanitizeCategory(e)
			if v == "" {
				continue
			}
			out = append(out, v)
		}
		cfg.Patterns.NER.Entities = out
	}
	if cfg.Patterns.NER.MinScore < 0 {
		cfg.Patterns.NER.MinScore = 0
	}
	if cfg.Patterns.NER.MinScore > 1 {
		cfg.Patterns.NER.MinScore = 1
	}

	// Targets
	if len(cfg.Targets) > 0 {
		out := make([]TargetConfig, 0, len(cfg.Targets))
		for _, t := range cfg.Targets {
			h := strings.TrimSpace(t.Host)
			if h == "" {
				continue
			}
			out = append(out, TargetConfig{Host: h, Enabled: t.Enabled})
		}
		cfg.Targets = out
	}

	// AuditDB
	cfg.AuditDB.Path = strings.TrimSpace(cfg.AuditDB.Path)
	if cfg.AuditDB.Path == "" {
		cfg.AuditDB.Path = defaultConfig.AuditDB.Path
	}
	cfg.AuditDB.Retention = strings.TrimSpace(cfg.AuditDB.Retention)
	if cfg.AuditDB.Retention == "" {
		cfg.AuditDB.Retention = defaultConfig.AuditDB.Retention
	}
}

// Get returns the current configuration
func (m *Manager) Get() Config {
	m.mu.RLock()
	defer m.mu.RUnlock()
	return m.config
}

// Update applies a mutation function to the config and saves to disk
func (m *Manager) Update(fn func(*Config)) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	fn(&m.config)
	return m.saveLocked()
}

// saveLocked writes the current config to disk (must be called with mu held)
func (m *Manager) saveLocked() error {
	toSave, err := m.encryptPatternsForSave(m.config)
	if err != nil {
		return err
	}
	data, err := yaml.Marshal(&toSave)
	if err != nil {
		return err
	}
	cfgPath := m.configPath
	if cfgPath == "" {
		cfgPath = ConfigPath()
	}
	if err := os.MkdirAll(filepath.Dir(cfgPath), 0700); err != nil {
		return err
	}
	if err := os.WriteFile(cfgPath, data, 0600); err != nil {
		return err
	}
	// Best-effort: if the file already exists, WriteFile may not reset permissions; chmod again.
	_ = os.Chmod(cfgPath, 0600)
	return nil
}

// Watch starts watching for config file changes
func (m *Manager) Watch(onChange func()) error {
	m.mu.Lock()
	defer m.mu.Unlock()

	if m.watcher != nil {
		return nil // Already watching
	}

	watcher, err := fsnotify.NewWatcher()
	if err != nil {
		return err
	}
	m.watcher = watcher

	// Watch global config directory
	cfgPath := m.configPath
	if cfgPath == "" {
		cfgPath = ConfigPath()
	}
	cfgPath = filepath.Clean(cfgPath)
	globalDir := filepath.Dir(cfgPath)
	if err := watcher.Add(globalDir); err != nil {
		return err
	}

	// Watch project config if exists
	projectPath := m.projectPath
	if projectPath == "" {
		projectPath = ProjectConfigPath()
	}
	projectPath = filepath.Clean(projectPath)
	if _, err := os.Stat(projectPath); err == nil {
		if err := watcher.Add(filepath.Dir(projectPath)); err != nil {
			return err
		}
	}

	go func() {
		for {
			select {
			case event, ok := <-watcher.Events:
				if !ok {
					return
				}
				// Check if it's a config file change
				name := filepath.Clean(event.Name)
				if name == cfgPath || name == projectPath {
					slog.Info("Config file changed, reloading...")
					if err := m.Load(); err != nil {
						slog.Error("Failed to reload config", "error", err)
					} else if onChange != nil {
						onChange()
					}
				}
			case err, ok := <-watcher.Errors:
				if !ok {
					return
				}
				slog.Error("Config watcher error", "error", err)
			}
		}
	}()

	return nil
}

// Close stops the config watcher
func (m *Manager) Close() error {
	m.mu.Lock()
	defer m.mu.Unlock()

	if m.watcher != nil {
		return m.watcher.Close()
	}
	return nil
}

// mergeConfigs merges project config over global config
func mergeConfigs(global, project Config) Config {
	result := global

	// Merge keywords (append, not replace)
	if len(project.Patterns.Keywords) > 0 {
		result.Patterns.Keywords = append(result.Patterns.Keywords, project.Patterns.Keywords...)
	}

	// Merge regex patterns (append, not replace)
	if len(project.Patterns.Regex) > 0 {
		result.Patterns.Regex = append(result.Patterns.Regex, project.Patterns.Regex...)
	}

	// Merge builtin patterns (append, not replace)
	if len(project.Patterns.Builtin) > 0 {
		result.Patterns.Builtin = append(result.Patterns.Builtin, project.Patterns.Builtin...)
	}

	// Merge exclude patterns (append, not replace)
	if len(project.Patterns.Exclude) > 0 {
		result.Patterns.Exclude = append(result.Patterns.Exclude, project.Patterns.Exclude...)
	}

	// Merge secret file sources (append, not replace)
	if len(project.Patterns.SecretFiles) > 0 {
		result.Patterns.SecretFiles = append(result.Patterns.SecretFiles, project.Patterns.SecretFiles...)
	}

	// Merge rule lists (append, not replace)
	if len(project.Patterns.RuleLists) > 0 {
		result.Patterns.RuleLists = append(result.Patterns.RuleLists, project.Patterns.RuleLists...)
	}

	// NER: project-level settings can enable and/or override entities.
	if project.Patterns.NER.Enabled {
		result.Patterns.NER.Enabled = true
	}
	if strings.TrimSpace(project.Patterns.NER.PresidioURL) != "" {
		result.Patterns.NER.PresidioURL = project.Patterns.NER.PresidioURL
	}
	if strings.TrimSpace(project.Patterns.NER.Language) != "" {
		result.Patterns.NER.Language = project.Patterns.NER.Language
	}
	if len(project.Patterns.NER.Entities) > 0 {
		// Entities uses overwrite semantics.
		result.Patterns.NER.Entities = append([]string(nil), project.Patterns.NER.Entities...)
	}
	if project.Patterns.NER.MinScore != 0 {
		result.Patterns.NER.MinScore = project.Patterns.NER.MinScore
	}

	// Merge targets (append, not replace)
	if len(project.Targets) > 0 {
		result.Targets = append(result.Targets, project.Targets...)
	}

	// Override scalar values if set in project
	if project.Proxy.Listen != "" {
		result.Proxy.Listen = project.Proxy.Listen
	}
	if project.Proxy.PlaceholderPrefix != "" {
		result.Proxy.PlaceholderPrefix = project.Proxy.PlaceholderPrefix
	}
	if project.Proxy.InterceptMode != "" {
		result.Proxy.InterceptMode = project.Proxy.InterceptMode
	}
	if project.Proxy.WebSocketRedactionBeta {
		result.Proxy.WebSocketRedactionBeta = true
	}
	if project.Session.TTL != "" {
		result.Session.TTL = project.Session.TTL
	}
	if project.Session.MaxMappings != 0 {
		result.Session.MaxMappings = project.Session.MaxMappings
	}
	if project.Log.Level != "" {
		result.Log.Level = project.Log.Level
	}
	if project.Log.File != "" {
		result.Log.File = project.Log.File
	}

	// AuditDB: project-level can enable/override path/retention.
	if project.AuditDB.Enabled {
		result.AuditDB.Enabled = true
	}
	if strings.TrimSpace(project.AuditDB.Path) != "" {
		result.AuditDB.Path = project.AuditDB.Path
	}
	if strings.TrimSpace(project.AuditDB.Retention) != "" {
		result.AuditDB.Retention = project.AuditDB.Retention
	}

	return result
}
